apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: prod
  name: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: prod
    spec:
      containers:
        - env:
            - name: APP_KEY
            - name: APP_NAME
            - name: APP_URL
            - name: CACHE_VIEWS
            - name: DB_CONNECTION
            - name: DB_DATABASE
            - name: DB_HOST
            - name: DB_PASSWORD
            - name: DB_PORT
            - name: DB_USER
            - name: HASH_DRIVER
            - name: HOST
            - name: NODE_ENV
            - name: PORT
          image: prod
          name: checkpoint-api
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: prod-claim0
      restartPolicy: Always
      volumes:
        - name: prod-claim0
          persistentVolumeClaim:
            claimName: prod-claim0
status: {}
